### ISSUE TITLE
Provide better feedback when database creation fails

### ISSUE THREAD

**Issue by henry-hz** [commanded/eventstore#1]
Before reporting the error, many thanks for sharing the eventstore!

> $ mix event_store.create  
> The EventStore database has been created.
> *\* (Postgrex.Error) ERROR (syntax_error): syntax error at or near "NOT"
>     (db_connection) lib/db_connection.ex:440: DBConnection.query!/4
>     (elixir) lib/enum.ex:608: Enum."-each/2-lists^foreach/1-0-"/2
>     (elixir) lib/enum.ex:608: Enum.each/2
>     lib/mix/tasks/event_store.create.ex:29: Mix.Tasks.EventStore.Create.run/1
>     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

**Comment by slashdotdash** [comment]
It's strange that it logged the "The EventStore database has been created." but also raised an error. The mix task uses `psql` to [create the database](https://github.com/slashdotdash/eventstore/blob/master/lib/event_store/storage/database.ex).

Did it actually create the database? If not you could manually create one to get started.

**Comment by henry-hz** [comment]
Thanks for the support, running:
PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
I will upgrade it.

**Comment by slashdotdash** [comment]
Fixed by #117.
