### ISSUE TITLE
Running `event_store.init` or `event_store.migrate` in a distillery release

### ISSUE THREAD

**Issue by HarenBroog** [commanded/eventstore#101]
Hi

Since usage of `mix` tasks in a release (e.g. created with `distillery`) is limited, I think we need substitutional way of setting up and migrating eventstore. `Ecto` introduced `Ecto.Migrator` which solves that problem. I didn't find any working method of doing it in environment mentioned above.

@slashdotdash do you have experience with deploying Elixir which contains `eventstore`, and  is packaged into the release with `distillery`?

EDIT:

ok its a duplicate of https://github.com/commanded/eventstore/issues/87 :)

**Comment by slashdotdash** [comment]
@HarenBroog I agree this needs to be done to make EventStore setup possible in an Elixir release. Happy to accept a pull request if you have time. 

I used `pg_dump` to create the EventStore database when I initially deployed to production. To upgrade I manually execute the migration SQL script in [priv/event_store/migrations](https://github.com/commanded/eventstore/tree/master/priv/event_store/migrations).

**Comment by mkaszubowski** [comment]
We've recently were doing this setup and we've just took the code from modules responsible for mix tasks and executed it inside remote console in the release.

If nobody else is interested, I think I might try to prepare a pull request which exposes those functions as a public interface (because right now it requires a bit of copy-pasting the code inside the remote console which isn't an optimal experience).

**Comment by HarenBroog** [comment]
@mkaszubowski I'm afraid that I don't have enough time and experience to provide the solution, so I'd love to see your PR with that :) I can offer my review of that changes.

**Comment by slashdotdash** [comment]
Fixed by #111.

**Comment by gottfrois** [comment]
@slashdotdash is there a place where we can find some examples of how to use those task with distillery? Thx

**Comment by slashdotdash** [comment]
@gottfrois I haven't tried this myself, but take a look at the [Distillery docs for running migrations](https://hexdocs.pm/distillery/guides/running_migrations.html). 

A similar approach should be possible based upon the existing Mix tasks in [`lib/mix/tasks`](https://github.com/commanded/eventstore/tree/master/lib/mix/tasks). 

Here's an example of a migrate function for Distillery as a release task:

```elixir
defp migrate(_argv) do
  {:ok, _} = Application.ensure_all_started(:postgrex)

  config = Config.parsed()

  Migrate.exec(config, [])
end
```

**Comment by gottfrois** [comment]
Thanks! I'm new to the elixir world so this code snippet really helps ❤️
