### ISSUE TITLE
Subscriptions broken when running on a single node (or is it me?)

### ISSUE THREAD

**Issue by vovayartsev** [commanded/eventstore#102]
Hi. First, let me apologize, I'm a newbie in Elixir and might have missed something very basic... but who knows... :)

1. I created a fresh new Phoenix app, added `eventstore` following [Getting Started](https://github.com/commanded/eventstore/blob/master/guides/Getting%20Started.md) guide

2. I created a sample consumer (following [this guide](https://github.com/commanded/eventstore/blob/master/guides/Subscriptions.md)):
```
defmodule Subscriber do
  use GenServer

  def start_link do
    GenServer.start_link(__MODULE__, [])
  end

  def received_events(subscriber) do
    GenServer.call(subscriber, :received_events)
  end

  def init(events) do
    # subscribe to events from all streams
    {:ok, subscription} = EventStore.subscribe_to_all_streams("example_subscription", self())

    {:ok, %{events: events, subscription: subscription}}
  end

  def handle_info({:events, events}, %{events: existing_events, subscription: subscription} = state) do
    # confirm receipt of received events
    EventStore.ack(subscription, events)
    IO.puts "Received events: #{inspect events}"

    {:noreply, %{state | events: existing_events ++ events}}
  end

  def handle_call(:received_events, _from, %{events: events} = state) do
    {:reply, events, state}
  end
end
```

3. In one terminal window, I started the consumer:
```
iex(1)>  Subscriber.start_link
[debug] Creating subscription process on stream "$all" named: "example_subscription"
{:ok, #PID<0.314.0>}
```

4. In another terminal, I created an event
```
events = [
  %EventStore.EventData{
    event_type: "Elixir.ExampleEvent",
    data: %ExampleEvent{key: "value"},
    metadata: %{user: "someuser@example.com"},
  }
]
stream_uuid = UUID.uuid4()
expected_version = 0
:ok = EventStore.append_to_stream(stream_uuid, expected_version, events)
```

**Expected**
I thought the event should have been printed in the first terminal immediately

**Actual**
The event doesn't appear. Looks like LISTEN / NOTIFY doesn't work
Subscribing to a particular stream instead of "$all" doesn't help too

But if I restart the Subscriber in the first terminal, I can see on the screen the events which are already in the DB.

**ENVIRONMENT**
* eventstore 0.13.2
* Elixir 1.6.0 on MacOS
* PG 9.6.2 installed via Brew

PS: thanks for doing such a great job in CQRS direction!

**Comment by slashdotdash** [comment]
@vovayartsev Using PostgreSQL's `LISTEN` / `NOTIFY` is a new feature only present in the master branch, it's not yet published to Hex. 

You'll need to reference EventStore from GitHub in your `mix.exs` file:

```elixir
defp deps do
  [
     {:eventstore, github: "commanded/eventstore", override: true}
  ]
end
```

Then fetch mix dependencies (`mix deps.get`) and try again. Let me know if that doesn't work for you.

**Comment by vovayartsev** [comment]
@slashdotdash confirming, after fetching edge version and re-creating the DB it works like a magic! Thanks a lot 👍

**Comment by mkaszubowski** [comment]
@slashdotdash  Can you maybe give your opinion on how stable this feature is? I'm considering using evenstore in the project, but I'm not sure how much more work is still necessary.

The readme mentions that eventstore is already used in production, is this also true for `LISTEN`/`NOTIFY`?

**Comment by slashdotdash** [comment]
@mkaszubowski The `LISTEN` / `NOTIFY` changes are relatively new and have not yet been published to Hex, or used in production. I've been running EventStore in production since v0.7.0 in December 2016.

There's a comprehensive test suite covering usage of the event store, including subscriptions. Before publishing the next release I want to execute a long-running subscription (e.g. append an event once per second for a few hours, asserting that they are received by a subscription). So it's feature complete and tested; I simply want to verify long-running subscriptions before signing off.

**Comment by mkaszubowski** [comment]
@slashdotdash  Sure, thanks for the response :) So far it works quite well. I hope I won't find any issues, but if I'll let you know if I do.

**Comment by slashdotdash** [comment]
@mkaszubowski I've created [a long running subscription test](https://github.com/commanded/eventstore/blob/3434ce6b810bded944737db32fa78aaeb188d298/test/manual/long_running_subscription.exs) and left it going for 2.5hrs. All working fine.

**Comment by mkaszubowski** [comment]
@slashdotdash That's really great, thank you!
