### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by brezal** [commanded/eventstore#107]
My apologies for not knowing where to ask for help.

Am I misreading the benchmarks in the readme?

```
## AppendEventsBench
benchmark name                         iterations   average time
append events, single writer                  100   20288.68 µs/op
append events, 50 concurrent writers            2   582350.50 µs/op
```

For single writer, it's at around 49 writes/sec.
```
>>> 20288.68 / 1000000
2.028868e-2

>>> 1 / 0.02028868
49.2885687979701
```
And for 50 concurrent writers, it looks like it's just under 2 writes/sec

```
>>> 582350.50 / 1000000
0.5823505
```

**Comment by slashdotdash** [comment]
@brezal The append events benchmark is for writing 100 events in a batch. That's what the µs/op average time is measuring.

So for a single writer it's 0.02s per 100 events (4,929 events/sec) and for 50 concurrent writers it's 50 x 100 events in 0.58s (8,586 events/sec).
