### ISSUE TITLE
Handling re-subscription to stream

### ISSUE THREAD

**Issue by andersonmcook** [commanded/eventstore#113]
Referencing the [example persistent subscriber](https://github.com/commanded/eventstore/blob/b2251b9ba77c6d64af379e17ebeacc8ed95493c2/guides/Subscriptions.md#example-persistent-subscriber)...

Stopping the GenServer post-subscription and then restarting using the same `subscription_name` gets `{:error, :subscription_already_exists}`.   Is there a preferred method for checking that a subscription exists?  Or should I be subscribing with a unique name each time?  Or, perhaps, thinking about it entirely differently?

**Comment by andersonmcook** [comment]
Thanks for looking into it. Here's some more context, that might cause you to spot an error I'm making or reproduce it yourself.

I subscribe to a specific stream in the Subscriber GenServer on `init`.
```elixir
  def init(%{stream_id: stream_id, subscription_name: subscription_name} = state) do
    {:ok, subscription} = EventStore.subscribe_to_stream(stream_id, subscription_name, self())
    {:ok, %{state | subscription: subscription}}
  end
```

- In iex, I run `start_link` for the Subscriber, passing in `stream_id` and `subscription_name` as options, putting them into state.
- Capturing the `pid` from starting the Subscriber, I can confirm that it is alive.
- Attempting to start the Subscriber again gives me a MatchError: `{:error, {:already_started, #PID<0.893.0>}}`
- I stop the Subscriber with GenServer.stop(pid)
- I confirm the pid is dead
- I run `start_link` as before and ...
```bash
** (EXIT from #PID<0.887.0>) evaluator process exited with reason: an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :subscription_already_exists}
```

**Comment by slashdotdash** [comment]
If you use `GenServer.stop(pid, :shutdown)` to stop the server does it allow you to start the subscriber again? 

By default the `stop/3` call uses `:normal` as the reason, which doesn't trigger linked processes. That might explain why the subscription is still running, preventing you from reconnecting to it.

**Comment by andersonmcook** [comment]
I do get different behavior using `:shutdown`
(`start_sub` runs Subscriber.start_link)
```bash
iex(2)> {:ok, pid} = start_sub.()
{:ok, #PID<0.916.0>}
Subscription: #PID<0.917.0>
iex(3)> GenServer.stop(pid, :shutdown)
** (EXIT from #PID<0.887.0>) evaluator process exited with reason: shutdown

Interactive Elixir (1.5.3) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by slashdotdash** [comment]
Sorry, you also need to `Process.unlink(pid)` before stopping it or else the IEX shell also gets terminated as it is linked to the subscription process.

**Comment by andersonmcook** [comment]
In that case, I can unlink, and then stop with :shutdown and successfully restart/resubscribe.

**Comment by andersonmcook** [comment]
It seems to me I was interacting with it incorrectly in iex.  If that's all, then thanks for your help!

**Comment by slashdotdash** [comment]
Thanks for helping to track down the cause of the issue. It may be worth changing the subscription process so that it *should* be tracking `:normal` shutdown of its subscriber. That's possible to acheive by monitoring the process, not just linking them together.

**Comment by slashdotdash** [comment]
I've verified that subscriber `:normal` exits do also stop the subscription process.
