### ISSUE TITLE
Automatically populate `event_type` in EventStore.EventData

### ISSUE THREAD

**Issue by OleMchls** [commanded/eventstore#116]
Hey there,

This is really a neat project! While I am digging into the codebase and the usage of this I was wondering why I need to set `event_type` in `EventStore.EventData` especially when `data` is a Struct. The library could internally call `Atom.to_string/1` and only optionally allow an overwrite via setting `event_type`. 

Would you folks be open to a PR?

**Comment by slashdotdash** [comment]
The `event_type` string can be optionally used when deserializing events by your configured serializer module. 

Typically you'd create a module per event you persist:

```elixir
events = [
  %EventData{
    event_type: "Elixir.ExampleEvent",
    data: %ExampleEvent{..},
    metadata: %{"user" => "user@example.com"}
  }
]

:ok = EventStore.append_to_stream(source_stream_uuid, 0, events)
```

The `deserialize/2` function in the `EventStore.Serializer` behaviour module is passed the `event_type` for you to use as necessary in your serializer.

```elixir
defmodule EventStore.RecordedEvent do
  def deserialize(%RecordedEvent{} = recorded_event, serializer) do
    %RecordedEvent{data: data, metadata: metadata, event_type: event_type} = recorded_event

    %RecordedEvent{
      recorded_event
      | data: serializer.deserialize(data, type: event_type),
        metadata: serializer.deserialize(metadata, [])
    }
  end
end
```

The example JSON serializer, using the Poison library, deserializes events using the `type` option as follows:

```elixir
defmodule EventStore.JsonSerializer do
  @behaviour EventStore.Serializer

  def serialize(term) do
    Poison.encode!(term)
  end

  def deserialize(binary, config) do
    type =
      case Keyword.get(config, :type, nil) do
        nil -> []
        type -> type |> String.to_existing_atom() |> struct
      end

    Poison.decode!(binary, as: type)
  end
end
```

This is all done for you automatically when using [Commanded](https://github.com/commanded/commanded) with the EventStore.

**Comment by slashdotdash** [comment]
Right, I understand what you're proposing thanks to the code example. Yes, it would be useful to allow the `event_type` to be defaulted as you suggest when nil.
