### ISSUE TITLE
[question] Work on an ElasticSearch backend for eventstore

### ISSUE THREAD

**Issue by sebastialonso** [commanded/eventstore#125]
Hi Commanded team. Let me start by thanking you for such a great work!

My team and I are studying the feasibility of writing a port of eventstore in some NoSQL actor, such as Mongo or ElasticSearch. This is because we have build a nice little data analysis framework that works with an ElasticSearch backend. 

Now, we are interested in using Commanded for a CQRS application, but since no NoSql backends are available (I haven't been able to find one at least) I'm reading through the source code of Commanded, EventStore and the adapter for both, hoping to be able to write an ElasticSearch backend for EventStore.

I think I have more or less grasped the big picture, but now I'm having issues making the conceptual bridges between what EventStore sends to Postgres and the equivalent with, say, an bunch of ElasticSearch indexes.

Specifically, trying to understand the `eventstore/lib/event_store/storage/create_stream.ex` file and then, the `eventstore/lib/event_store/sql/statements.ex` file, I find that there are many tables, and I'm not sure if I should port all of them to ElasticSearch indexes or not.

Would it be possible to get a short context for each table and how they communicate together through EventStore? We are very eager to work with both EventStore and Commanded for our new projects. 

Thanks again!

**Comment by slashdotdash** [comment]
@sebastialonso The EventStore makes use of the following tables:

- `events` - stores the event data & metadata
- `streams` - one row per logical stream of events in the store, and each stream's version.
- `stream_events` - join table used to include an event in a stream.
- `subscriptions` - one row per subscriber, used to track the last successfull processed and acknowledged event to allow subscription to be resumed.
- `snapshots` - used to persist snapshot data, such as aggregate and process manager state.
- `schema_migrations` - used to record which EventStore database migrationd have been run when upgrading to a newer version.

EventStore also makes use of Postgres' `LISTEN` / `NOTIFY` feature for [event pub/sub to subscriptions](https://github.com/commanded/eventstore/blob/master/guides/Subscriptions.md#event-pubsub) and Postgres advisory locks to ensure only a [single instance of each subscription runs, regardless of how many nodes are running](https://github.com/commanded/eventstore/blob/b2251b9ba77c6d64af379e17ebeacc8ed95493c2/guides/Cluster.md#subscriptions).

**Comment by sebastialonso** [comment]
Great, I'll give it a read.
Thank you very much Ben!
