### ISSUE TITLE
[question] Is there any reason not to use timestamp with time zone?

### ISSUE THREAD

**Issue by datafoo** [commanded/eventstore#147]
I see that the timestamp used for `event.created_at` is defined as a `timestamp without time zone` and a comment states that:
`created_at - the date/time, in UTC, indicating when the event was
      created.` [line 23](https://github.com/commanded/eventstore/blob/3b4040b742cbccea5b6a9dd2c0e8628b4845ae84/lib/event_store/recorded_event.ex)

Since it is explicitly _described_ in reference to UTC, why not also use `timestamp with time zone` to explicitly _store_ it in reference to UTC? Same question for timestamps on other tables.

**Comment by slashdotdash** [comment]
@datafoo I can't remember the reasoning behind storing all datetimes without a timezone (and hence using `NaiveDateTime`). 

I don't have a strong view on storing datetimes either with or without a timezone. If you feel that storing the timezone would be preferable then feel free to submit a PR, or leave this issue open and it can be picked up at some point in the future to implement.

**Comment by slashdotdash** [comment]
Fixed by #150.
