### ISSUE TITLE
[question] How to parse a JSON string into a DateTime struct when using jsonb?

### ISSUE THREAD

**Issue by datafoo** [commanded/eventstore#149]
Similar to the explanation provided in the [documentation](https://hexdocs.pm/commanded/serialization.html) (see extract below), I would like to parse an event field string into a `DateTime` struct.
```elixir
defmodule ExampleEvent do
  defstruct [:name, :date]
end

defimpl Commanded.Serialization.JsonDecoder, for: ExampleEvent do
  @doc """
  Parse the date included in the event
  """
  def decode(%ExampleEvent{date: date} = event) do
    %ExampleEvent{event |
      date: NaiveDateTime.from_iso8601!(date)
    }
  end
end
```

However, I am not using `Commanded.Serialization.JsonSerializer` but `EventStore.JsonbSerializer` as indicated in [documentation](https://hexdocs.pm/eventstore/getting-started.html#using-the-jsonb-data-type) when using the `jsonb` data type.

Unless I am missing something, `EventStore.JsonbSerializer` does not provide an extension point to allow additional decoding of the deserialized value as `Commanded.Serialization.JsonSerializer` does.

What is the recommended way to achieve this when using `jsonb`?

**Comment by slashdotdash** [comment]
You can use the following [JsonbSerializer](https://gist.github.com/slashdotdash/d28feba38469604ea3346b257bfda73d) which combines the EventStore jsonb serializer with support for Commanded’s JSON decode protocol.

**Comment by datafoo** [comment]
Thank you. I imagine this case is not uncommon. Why not pulling these changes in the repository?

**Comment by slashdotdash** [comment]
Closing issue as the linked JsonbSerializer can be used if needed. It cannot be included in the EventStore library because it references Commanded's `Commanded.Serialization.JsonDecoder` protocol.
