### ISSUE TITLE
[question] Why the term "CQRS event store" appears in this repository?

### ISSUE THREAD

**Issue by datafoo** [commanded/eventstore#151]
The term "CQRS event store" appears in 2 [occasions](https://github.com/commanded/eventstore/search?q=cqrs&unscoped_q=cqrs) in this repository.

Event though an event store is needed when using CQRS, I believe using this event store does not only apply to CQRS, isn't?

Should renaming "CQRS event store" to just "event store" better represent what this project is about?

**Comment by slashdotdash** [comment]
Yes, we could drop the term CQRS since this library is an event store which can be used without applying CQRS.
