### ISSUE TITLE
module EventStore.PostgresTypes is not available

### ISSUE THREAD

**Issue by mwillema** [commanded/eventstore#153]
According to the [Getting Started guide](https://github.com/commanded/eventstore/blob/master/guides/Getting%20Started.md) we should add this line to `config.exs` when we want to use the jsonb datatype:
```
types: EventStore.PostgresTypes
```
However this results in a module not available error. Without the afford mentioned line it seems to work.

**Comment by slashdotdash** [comment]
You need to [include the Jason library](https://github.com/commanded/eventstore/blob/master/guides/Event%20Serialization.md#json-serialization-using-jason) in `mix.exs` to enable the Postgrex types with JSON support.

```elixir
defp deps do
  [{:jason, "~> 1.1"}]
end
```

**Comment by mwillema** [comment]
Ok thanks for the reply :-) IMO this should probably be mentioned in the documentation. I can do it if you want.

**Comment by slashdotdash** [comment]
Yes, it would be useful to include in the docs. A pull request would be gladly accepted.
