### ISSUE TITLE
[question] Protobuf serializer

### ISSUE THREAD

**Issue by mwillema** [commanded/eventstore#156]
Has a [Protocol Buffers](https://developers.google.com/protocol-buffers/) serializer already been implemented for this Event Store?

**Comment by slashdotdash** [comment]
Not that I have encountered, no. Anyone else?

**Comment by mwillema** [comment]
I wrote one for my company's current project. I'd be glad to share it if you're interested.

**Comment by slashdotdash** [comment]
I'm sure that would be useful for anyone considering using ProtoBufs. Can you share it as a Gist?

**Comment by mwillema** [comment]
Here it is: [protobuf_serializer.ex](https://gist.github.com/mwillema/069233ddffb3f7b1d1bb6f1081b86fd8)
It's an idea (see my comments regarding the serialization of metadata) and it is using the [protobuf-elixir](https://github.com/tony612/protobuf-elixir) project.
