### ISSUE TITLE
Event stream deletion

### ISSUE THREAD

**Issue by slashdotdash** [commanded/eventstore#170]
Allow an event stream to be soft or hard deleted. 

- Soft deletion will make the stream unreadable, but keep the events in the database.

  ```elixir
  :ok = EventStore.delete_stream(stream_uuid, :soft)
  ```

- Hard delete will remove the stream and its events from the database.

  ```elixir
  :ok = EventStore.delete_stream(stream_uuid, :hard)
  ````

Events are included in the global `$all` stream by default. When a stream is deleted the events should also be removed from this stream.

**Comment by Freyskeyd** [comment]
How do we manage event numbers in case of deleted events ?
