### ISSUE TITLE
Allow event store operations to use a supplied database connection or transaction

### ISSUE THREAD

**Issue by slashdotdash** [commanded/eventstore#176]
It can be useful to append events to an event store within the same database transaction as projecting those events into the read model (when using the same database). 

This would be possible by allowing the user to provide an existing database connection or transaction to any applicable event store function:

```elixir
{:ok, pid} = Postgrex.start_link(config)

Postgrex.transaction(pid, fn conn ->
  # Append events to a stream using transaction `conn`
  :ok = EventStore.append_to_stream(stream_uuid, expected_version, events, conn: conn)

  # Project events into read model within same database transaction
  for event <- events do
    :ok = Projector.project(conn, event)
  end
end)
```

Writing to multiple streams within a single transaction could also be supported with this approach.

**Comment by kaikuchn** [comment]
This is a feature that would be highly appreciated! In fact my team mates and I are pretending that this already works and wrap our calls to `append_to_stream` in `Multi.run`.

Can you give us some pointers on what would need to be done to get this to work?

Best regards,
Kai

**Comment by slashdotdash** [comment]
@kaikuchn This could be a small change to make. It would require allowing a Postgrex connection or transaction to be passed to all of the public functions in the `EventStore` module, such as `append_to_stream`, as part of the `opts` argument. Then the [`parse_opts/1`](https://github.com/commanded/eventstore/blob/818df8dc4c54b7e8ecb189ad60c31663da3212c0/lib/event_store.ex#L410) function would need to find the `conn` from the `opts` if provided, or fallback to what it does currently and look in the `config`. That might be all that is required.

**Comment by slashdotdash** [comment]
@kaikuchn I've written up how to [access an Ecto Repo's database connection process](https://github.com/slashdotdash/til/blob/master/elixir/ecto-repo-connection-process.md). This will hopefully be a suitable process for the EventStore functions.

**Comment by slashdotdash** [comment]
Done in #231.
