### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by ilgarm** [commanded/eventstore#177]
Hello, when next release is planned?
Thanks, Ilgar.

**Comment by slashdotdash** [comment]
It is coming _very soon_! 

I've just been [upgrading the Conduit example repo](https://github.com/slashdotdash/conduit/commit/7e8bde5dbb19cce80673f01727528a835e733817) to use the latest Commanded and EventStore libraries from GitHub (`master` branches) which have support for defining multiple apps/stores. The test suite passed successfully after the upgrade. I wanted to run through the upgrade step on a "real world" application to ensure it all worked together and to have an idea of the steps required which I can use to document the Commanded and Event Store upgrade guides.

Given the above success I will publish a `v1.0.0-rc.0` release candidate for Commanded, Event Store, and support libraries to Hex this week.

**Comment by ilgarm** [comment]
That is really great. Thank you for your feedback!
