### ISSUE TITLE
[Doc] Running mix tasks using Elixir releases

### ISSUE THREAD

**Issue by slashdotdash** [commanded/eventstore#178]
The EventStore mix tasks, such as `mix event_store.create`, delegate the actual work to corresponding task modules defined inside EventStore (in `lib/mix/tasks`) so you can use them directly:

- [`Tasks.EventStore.Create`](https://github.com/commanded/eventstore/blob/v1.0.0-rc.0/lib/event_store/tasks/create.ex)
- [`Tasks.EventStore.Init`](https://github.com/commanded/eventstore/blob/v1.0.0-rc.0/lib/event_store/tasks/init.ex)
- [`Tasks.EventStore.Migrate`](https://github.com/commanded/eventstore/blob/v1.0.0-rc.0/lib/event_store/tasks/migrate.ex)

Mix releases support [running one-off commands](https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-one-off-commands-eval-and-rpc) and using a helper module to define these commands, example below. 

```elixir
defmodule MyApp.ReleaseTasks do
  def init_event_store do
    {:ok, _} = Application.ensure_all_started(:postgrex)
    {:ok, _} = Application.ensure_all_started(:ssl)
    
    :ok = Application.load(:eventstore)

    config = EventStore.Config.parsed()

    EventStore.Tasks.Create.exec(config, [])
    EventStore.Tasks.Init.exec(config, [])
  end
end
```

Run a release task:

```
bin/RELEASE_NAME eval "MyApp.ReleaseTasks.init_event_store()"
```

**Comment by norpan** [comment]
Just wanted to note here that you now (version 1.0)  have to do `Your.EventStore.config()` instead of `EventStore.Config.parsed()`.
