### ISSUE TITLE
:erlang.binary_to_existing_atom fails when using eventstore in combination with a phoenix app

### ISSUE THREAD

**Issue by badazz91** [commanded/eventstore#193]
when using eventstore in a phoenix app the app crashes when it already has events stored in the db.

when starting it with an empty db, there are no problems.

when restarting it after some time for the 2nd - Nth time I get this issue

```
08:41:16.221 [error] Task #PID<0.1078.0> started from #PID<0.984.0> terminating
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("travelled", :utf8)
    (eventstore) lib/event_store/jsonb_serializer.ex:35: anonymous fn/2 in EventStore.JsonbSerializer.keys_to_atoms/1
    (stdlib) maps.erl:232: :maps.fold_1/3
    (eventstore) lib/event_store/jsonb_serializer.ex:34: EventStore.JsonbSerializer.keys_to_atoms/1
    (eventstore) lib/event_store/jsonb_serializer.ex:30: EventStore.JsonbSerializer.to_struct/2
    (eventstore) lib/event_store/recorded_event.ex:63: EventStore.RecordedEvent.deserialize/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (eventstore) lib/event_store/streams/stream.ex:230: EventStore.Streams.Stream.read_storage_forward/6
    (eventstore) lib/event_store/streams/stream.ex:264: anonymous fn/6 in EventStore.Streams.Stream.stream_storage_forward/6
    (elixir) lib/stream.ex:1407: Stream.do_resource/5
    (elixir) lib/enum.ex:3023: Enum.reverse/1
    (elixir) lib/enum.ex:2670: Enum.to_list/1
```

I am using this config (the module that is using eventstore internally is called :logbook):

```
config :logbook, Logbook.EventStore,
  column_data_type: "jsonb",
  serializer: EventStore.JsonbSerializer,
  types: EventStore.PostgresTypes,
  username: "user",
  password: "pw",
  database: "logbook",
  hostname: "localhost"
```

I am using this env:
```
iex -S mix phx.server
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by badazz91** [comment]
I suspect that it has something to with this line:

lib/event_store/jsonb_serializer.ex:35: 
```    {String.to_existing_atom(key), keys_to_atoms(value)} ```

**Comment by slashdotdash** [comment]
The default JSON serializers expect all keys within persisted event to be existing atoms. This might be problematic if you allow dynamic data within an event, such as a map of user-defined key/value pairs. 

You could copy & paste the `JsonbSerializer` into your own app and modify `String.to_existing_atom` to use `String.to_atom` if that suits your usage better. Alternatively, you could consider using string keys for maps in events and change the `keys_to_atoms` function to be non-recursive, as shown:

```elixir
defp keys_to_atoms(map) when is_map(map) do
  for {key, value} <- map, into: %{} do
    {String.to_existing_atom(key), value}
  end
end
```

**Comment by badazz91** [comment]
my event in question looks like this:

```
defmodule Logbook.Events.RouteDetected do
  alias __MODULE__

  defstruct [:id, :start, :stop, :travelled, :kilometrage, :license_plate]

  def create(%{
        id: id,
        distance: distance,
        start: start,
        end: stop,
        kilometrage: kilometrage,
        license_plate: license_plate,
        starting_position: starting_position,
        stop_position: stop_position
      }) do
    %RouteDetected{
      id: id,
      travelled: distance,
      kilometrage: kilometrage,
      license_plate: license_plate,
      start: starting_position |> Map.merge(%{time: start}),
      stop: stop_position |> Map.merge(%{time: stop})
    }
  end
end
```

e.g. start and stop is also a nested struct.

this could be the problem?

so solution would be to have "flat" events, without nested data?

@slashdotdash

**Comment by slashdotdash** [comment]
I prefer flat events with minimal nesting for the type safety provided by structs. 

Commanded does have support for decoding nested event structs via the [`Commanded.Serialization.JsonDecoder`](https://hexdocs.pm/commanded/serialization.html#decoding-event-structs) protocol allowing you to support nested structures.

**Comment by badazz91** [comment]
I think this solves the issue. Thanks for helping out!

**Comment by badazz91** [comment]
Ok I tried out flattening the event completely out. no more nested structs.

still this error occurs 
```
14:07:16.974 [error] Task #PID<0.845.0> started from #PID<0.824.0> terminating
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("start_city", :utf8)
    (eventstore) lib/event_store/jsonb_serializer.ex:35: anonymous fn/2 in EventStore.JsonbSerializer.keys_to_atoms/1
```

I think it is related to the recursive calling of  ``` keys_to_atoms ```

Really strange @slashdotdash

**Comment by slashdotdash** [comment]
If `start_city` doesn't exist somewhere in your code as an atom then the above will fail. 

Try using `String.to_atom` instead. You will need to copy & paste the serializer into your project, modify, and configure the event store to use it.

**Comment by badazz91** [comment]
Ok I ll try that.

concerning this
> If start_city doesn't exist somewhere in your code as an atom then the above will fail.

the strange thing is that it is defined in the event struct.
```
defmodule Logbook.Events.RouteDetected do
  alias __MODULE__

  defstruct [
    :id,
    :travelled,
    :kilometrage,
    :license_plate,
    :start_time,
    :start_city,
    :start_country,
    :start_latitude,
    :start_longitude,
    :start_street,
    :start_zip,
    :stop_time,
    :stop_city,
    :stop_country,
    :stop_latitude,
    :stop_longitude,
    :stop_street,
    :stop_zip
  ]
end

**Comment by badazz91** [comment]
@slashdotdash 

> Try using String.to_atom instead. You will need to copy & paste the serializer into your project, modify, and configure the event store to use it.

using custom serializer does the trick.

Still I am struggeling to understand why it does not work with default jsonb serializer and flat events,a and all keys present in the defstruct.

**Comment by slashdotdash** [comment]
@badazz91 No, I can't see why `String.to_existing_atom` fails when the atom exists in the event struct. One reason could be if the event module hasn't been loaded before the call is made. This might happen with dynamic module loading or reloading.

**Comment by badazz91** [comment]
Thanks for the help.

if I find out some additional info somewhere along the way, I ll update you!
