### ISSUE TITLE
What ist the simplest way to link events to other streams on append

### ISSUE THREAD

**Issue by arfl** [commanded/eventstore#195]
Hello.
First of all: thank you for this great library! It is the backbone of almost all of our applications!

I need some assistance concerning the event linking.

First, I append an event to the event store. 
```
my_business_event = MyApp.ProductSold.new(user_id: user_id, product_id: product_id, more_info: "Foo")

events = [
  %EventData{
    event_type: "MyApp.SomeEvent",
    data: my_business_event,
    metadata: %{user: "someuser@example.com"},
  }
]

:ok = MyApp.EventStore.append_to_stream(event.product_id, :any_version, events)
```
Now, I would like to link `my_business_event` to the stream `my_business_event.user_id`. What is the simplest way to do it? Do I need to read all the events from `my_business_event.product_id` stream first? It could be several thousand...

Thank you!

**Comment by slashdotdash** [comment]
One option would be to have a separate process create a subscription (to all events) and have it do the linking whenever it encounters an event of the given type in a product stream.

```elixir
def handle_info({:events, events}, %{subscription: subscription} = state) do
  for event <- events do
    if event.event_type == "MyApp.SomeEvent" do
      :ok = MyApp.EventStore.link_to_stream(event.data.user_id, :any_version, [event.id])
    end
  end

  :ok = MyApp.EventStore.ack(subscription, events)

  {:noreply, subscription}
end
```

**Comment by arfl** [comment]
That's a pretty simple solution! Thank you!!!
