### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by zamith** [commanded/eventstore#219]
I'm using eventstore in a multi tenancy setup with multiple databases (as opposed to database schemas), and am able to start multiple instances of the eventstore just fine, however it requires me to have a compile time config (which it will spin up). I'm not using this instance and would be great if it would be optional, I just want the runtime ones for each of the tenants.

Any way of doing this currently?

**Comment by zamith** [comment]
@slashdotdash Secondary question. How can I run the mix tasks with dynamic eventstore configurations? In particular I want to be able to configure how it connects to the database.

**Comment by zamith** [comment]
I was able to do it by creating my own mix tasks around the tasks modules. Is that the idea?

**Comment by slashdotdash** [comment]
Yes, for dynamic event stores you will need to write your own application specific Mix tasks to iterate over the source (such as a list of tenants) and run the EventStore create, init, or migrate tasks.
