### ISSUE TITLE
Backend agnostic

### ISSUE THREAD

**Issue by Papipo** [commanded/eventstore#22]
Hi!

I think that it could be interesting to separate the storage backend and make it configurable.
I actually like PostgreSQL but it would be nice to be able to use something like Apache Kafka, which is built with partitioning in mind, or for less demanding scenarios, NoSQL databases.

Thanks.

**Comment by henry-hz** [comment]
:+1:

**Comment by slashdotdash** [comment]
The PostgreSQL specific code currently lives in [lib/event_store/storage](https://github.com/slashdotdash/eventstore/tree/master/lib/event_store/storage) and [lib/event_store/sql](https://github.com/slashdotdash/eventstore/tree/master/lib/event_store/sql). 

I imagine it would be possible to define a behaviour that encompasses the API required to plug in another storage provider. Then extract the existing PostgreSQL implementation into a separate library. Alternative storage providers could be written in a similar approach.

I don't have plans to implement this in the near term, but it could be a good future enhancement.

**Comment by henry-hz** [comment]
Thanks for the feedback, implementing for MySQL should be smooth. Google Big Table could be an interesting option too, maybe when needed...

**Comment by boxxxie** [comment]
I think there are a lot of backends that people will want to use, Apache bookkeeper/twitter distributed log/kafka... 
are all of these configurations, or more, going to be merged in when they are made? is there a way for me to support a backend without me having to for this repo or get a backend merged in?

**Comment by slashdotdash** [comment]
@boxxxie The first step would be to define a contract for the storage provider (e.g. an Elixir behaviour). Then to create a providing using the existing PostgreSQL implementation. Additional storage adapters could be written as stand-alone libraries. They just implement the behaviour defined in this library.

This feature is on the roadmap, but no definite timeline.

**Comment by imetallica** [comment]
@slashdotdash: Would be interesting to move the datastorage to work with Ecto (latest version)? By using it we would be supporting Maria/MySQL as well, as also using Repo to handle database connections.

**Comment by tslater** [comment]
I'm curious what the thoughts are on using ecto as an abstraction point. I briefly looked at the code, and it looks like it wouldn't be trivial, but is it a bad idea or good idea in general? I'm not familiar enough to have an opinion. Before digging deeper, I'd like to know what @slashdotdash, or anyone else familiar thinks of that.

**Comment by slashdotdash** [comment]
@tslater It's worth doing a spike to integrate Ecto for event persistence and then compare with the PostgreSQL-only current implementation. It would be great if Ecto could be included to provide the EventStore with multi database support.
