### ISSUE TITLE
JSONB vs BYTEA for storing events?

### ISSUE THREAD

**Issue by harukizaemon** [commanded/eventstore#47]
How difficult would it be to support JSONB as the storage for the event data and metadata?

**Comment by slashdotdash** [comment]
The event store has been designed to be serialization format agnostic. You implement the `EventStore.Serializer` behaviour in your own module and use whatever serializer you prefer: Erlang term, JSON, MessagePack, ProtocolBuffers, etc. Therefore the event data & metadata are persisted as binary data.

It would be possible to add support for alternative column data types (e.g. BYTEA or JSONB). What would be the benefits of supporting JSONB?

**Comment by harukizaemon** [comment]
For context, I have a largish production app I've been looking at cutting over to Elixir. I came across your blog posts and repositories and thought: this is wonderful! And I'm looking to see how much compromise in either direction is possible to make the switch. And of course, I totally understand that accomodating me isn't exactly top priority and nor should it be :)

>The event store has been designed to be serialization format agnostic.

Yup. That makes sense and fits with my reading of the code. Totally get the rationale therefore for wanting a format agnostic storage mechanism.

>What would be the benefits of supporting JSONB?

Mostly it means that the generated JSON is stored natively in PostgreSQL. There have been situations where being able to use standard PostgreSQL queries have allowed us to debug and resolve production issues. It also means that other tools can can for whatever reason -- in my case perhaps the long tail of a legacy codebase and production database that will take time to move across.

**Comment by DominikGuzei** [comment]
@harukizaemon do you have written a Postgres serializer that you could share? I also want to have human readable JSON as event data.

**Comment by slashdotdash** [comment]
Fixed by #86.
