### ISSUE TITLE
Database schema migration task

### ISSUE THREAD

**Issue by slashdotdash** [commanded/eventstore#56]
To support database schema migrations made between releases, it would be helpful to provide a mix task to migrate an Event Store database:

```elixir
mix event_store.migrate
```

The behaviour would be similar to Ecto's [Ecto.Migrator](https://hexdocs.pm/ecto/Ecto.Migrator.html). 

1. Define a migration SQL script (e.g. `ALTER TABLE events ADD causation_id text;`).
2. Record execution of each migration script to ensure it executes only once.

**Comment by davich** [comment]
This would be great!

**Comment by slashdotdash** [comment]
Done by 20e0421.
