### ISSUE TITLE
Support PostgreSQL named schemas

### ISSUE THREAD

**Issue by anthonator** [commanded/eventstore#64]
Postgres has the ability to partition database tables into separate schemas within the same database. It would be great if EventStore could be configured to use a named schema.

Ecto supports this by passing a `prefix` when creating a table/index/whatever. I know this project doesn't use Ecto but I thought it might be a good example.

https://www.postgresql.org/docs/9.6/static/ddl-schemas.html

**Comment by slashdotdash** [comment]
@anthonator Yes, I agree this would be a useful feature to add. Added to the backlog.

**Comment by slashdotdash** [comment]
Done in #182.
