### ISSUE TITLE
Support multiple event stores

### ISSUE THREAD

**Issue by slashdotdash** [commanded/eventstore#76]
Allow multiple event stores to be used in an application by providing an `EventStore` macro to use in your own module, as per Ecto's repo.

Define your event store module:

```elixir
defmodule MyApp.EventStore do
  use EventStore, 
    otp_app: :my_app

  # Optional `init/1` function to modify config at runtime.
  def init(config) do
    {:ok, config}
  end
end
```

Configure the event store:

```elixir
config :my_app, MyApp.EventStore,
  serializer: EventStore.TermSerializer,
  username: "postgres",
  password: "postgres",
  database: "eventstore_dev",
  hostname: "localhost",
  pool_size: 10,
  pool_overflow: 5

config :my_app, event_stores: [MyApp.EventStore]
```

Usage:

```elixir
:ok = MyApp.EventStore.append_to_stream(stream_uuid, expected_version, events)
```

**Comment by hauleth** [comment]
This would provide additional pro: there could be `init` callback like in Ecto that would allow to load configuration in runtime instead of relying on some weird tooling.

**Comment by slashdotdash** [comment]
Work in progress on branch [`feature/multi-event-store`](https://github.com/commanded/eventstore/tree/feature/multi-event-store).

**Comment by slashdotdash** [comment]
Done in #168.
