### ISSUE TITLE
Create command fails to setup database correctly.

### ISSUE THREAD

**Issue by eamontaaffe** [commanded/eventstore#85]
On only versions above v0.13.0 I am having trouble creating a fresh database. 

On the latest master branch (Release v0.13.2), when I run:

```bash
MIX_ENV=test mix event_store.drop
MIX_ENV=test mix event_store.create
mix test
```

The output is:

```bash
=INFO REPORT==== 12-Nov-2017::21:44:40 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application eventstore: EventStore.Application.start(:normal, []) returned an error: shutdown: failed to start child: EventStore.Publisher
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in EventStore.Storage.QueryLatestEventNumber.handle_response/1
            (eventstore) lib/event_store/storage/query_latest_event_number.ex:11: EventStore.Storage.QueryLatestEventNumber.handle_response({:error, %Postgrex.Error{connection_id: 59103, message: nil, postgres: %{code: :undefined_table, file: "parse_relation.c", line: "1160", message: "relation \"event_counter\" does not exist", pg_code: "42P01", position: "26", routine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}}})
            (eventstore) lib/event_store/publisher.ex:26: EventStore.Publisher.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

As you can see from the error message, the expected table does not exist. When I check the postgres instance, there are no tables created in the new database. The `mix event_store.create` does not output any errors or warnings.

I get the same response when checking out v0.13.1 and v0.13.0. Any releases before that, such as v0.12.1, work as expected and setup the database correctly. Also the test suites pass.

My postgres version is 9.6.2.

**Comment by eamontaaffe** [comment]
My mistake, didn't realise there was a new series of commands with v0.13.0 onwards:

```bash
mix do event_store.drop, event_store.create, event_store.init
```

**Comment by slashdotdash** [comment]
@eamontaaffe Glad to hear you found the solution. Splitting the database create and initialisation into separate tasks was to allow an existing PostgreSQL database to be used for the event store. But it does mean more typing is required when creating one from scratch.
