### ISSUE TITLE
Disabling `:info` level logging

### ISSUE THREAD

**Issue by ashutoshrishi** [commanded/eventstore#90]
In our app we are attaching a `Logger` backend to transport logs to an online logging service (Timber). Since `eventstore` as a single `Logger.info` running after every event is recorded, it produces a lot of log noise (events are expected at a very short interval over long periods of time). 

Is it possible to convert this into a `:debug` log or have a configurable logger. 

Or is there any way `Logger` can be turned off for certain apps? 

https://github.com/commanded/eventstore/blob/20b3cb6f20ca59fc336e9682dd5fd36968fd5f27/lib/event_store/storage/appender.ex#L82-L87

**Comment by slashdotdash** [comment]
@ashutoshrishi Yes, I'm happy to lower the logging level to `:debug` for that message.

**Comment by ashutoshrishi** [comment]
@slashdotdash Hey, the commit https://github.com/commanded/eventstore/commit/5d8b7b64cf7493716504702ae9d367ce1cd3ed97 does not feature in the recent releases on hex.

**Comment by slashdotdash** [comment]
@ashutoshrishi Yes, there are seven fixes/enhancements scheduled for the next release ([CHANGELOG](https://github.com/commanded/eventstore/blob/master/CHANGELOG.md)). I'd like to document the `jsonb` changes and try to write a migration script, or mix task, before releasing.
